options:
   logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/myfirstapp-72240/ica4-frontend:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/myfirstapp-72240/ica4-frontend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/ica4-frontend-deployment'
      - 'ica4-frontend=gcr.io/myfirstapp-72240/ica4-frontend:$SHORT_SHA'
      - '--namespace=ica4-frontend'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
images:
  - 'gcr.io/myfirstapp-72240/ica4-frontend:$SHORT_SHA'
substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'ica4-cluster'

