apiVersion: v1
kind: Namespace
metadata:
  name: assignment-02-frontend

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment-02-frontend-configmap
  namespace: assignment-02-frontend
data:
  REACT_APP_BACKEND_URL: "get the external ip address of the backend"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-02-frontend-deployment
  namespace: assignment-02-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment-02-frontend-app
  template:
    metadata:
      labels:
        app: assignment-02-frontend-app
    spec:
      containers:
        - name: assignment-02-frontend
          image: gcr.io/myfirstapp-72240/assignment-02-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: assignment-02-frontend-configmap
      imagePullSecrets:
        - name: gcr-json-key

---

apiVersion: v1
kind: Service
metadata:
  name: assignment-02-frontend-service
  namespace: assignment-02-frontend
spec:
  type: LoadBalancer
  selector:
    app: assignment-02-frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
