apiVersion: v1
kind: Namespace
metadata:
  name: ica4-frontend

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ica4-frontend-configmap
  namespace: ica4-frontend
data:
  REACT_APP_BACKEND_URL: "http://backend-service.backend.svc.cluster.local"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ica4-frontend-deployment
  namespace: ica4-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ica4-frontend-app
  template:
    metadata:
      labels:
        app: ica4-frontend-app
    spec:
      containers:
        - name: ica4-frontend
          image: gcr.io/myfirstapp-72240/ica4-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ica4-frontend-configmap
      imagePullSecrets:
        - name: gcr-json-key

---

apiVersion: v1
kind: Service
metadata:
  name: ica4-frontend-service
  namespace: ica4-frontend
spec:
  type: LoadBalancer
  selector:
    app: ica4-frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
