apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: ica4frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: gcr.io/myfirstapp-72240/frontend-app:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-app-config
                  key: REACT_APP_BACKEND_URL
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  name: frontend-app-config
                  key: GOOGLE_APPLICATION_CREDENTIALS
      imagePullSecrets:
        - name: gcr-json-key

