apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  namespace: ica4frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
        - name: frontendapp
          image: gcr.io/cbd3354-435500/frontendapp:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontendapp-config
                  key: REACT_APP_BACKEND_URL
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  name: frontendapp-config
                  key: GOOGLE_APPLICATION_CREDENTIALS

