name: CI/CD Pipeline Kubernetes Deployment

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: kubectl

      # Step 4: Authenticate kubectl to GKE
      - name: Authenticate kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GKE_CLUSTER_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      # Step 5: Apply Kubernetes manifests
      - name: Apply Kubernetes ConfigMap
        run: |
          kubectl apply -f /mnt/data/configmap.yaml --namespace=ica4backend

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f /mnt/data/deployment.yaml --namespace=ica4backend
